tasks:
  - init: |
      curl -O https://raw.githubusercontent.com/extism/js-pdk/main/install.sh
      sh install.sh
      curl -s https://get.extism.org/cli | sh
  - command: extism --help  # Optional: Verify that Extism CLI is installed correctly
